"""Recreate database

Revision ID: a307ce900dd9
Revises: d6ed1c5b7847
Create Date: 2023-11-25 15:42:09.520562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a307ce900dd9'
down_revision = 'd6ed1c5b7847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('food_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('orders_food_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key('orders_food_id_fkey', 'food_items', ['food_id'], ['id'])
        batch_op.alter_column('food_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
